name: novartis-dsai
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - cairo=1.14.12
  - certifi=2019.9.11
  - curl=7.65.3
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gsl=2.4
  - harfbuzz=1.8.8
  - icu=58.2
  - jpeg=9b
  - krb5=1.16.1
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - make=4.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.43
  - pip=19.3.1
  - pixman=0.38.0
  - python=3.6.9
  - r=3.6.0
  - r-base=3.6.1
  - r-boot=1.3_20
  - r-class=7.3_15
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-foreign=0.8_71
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_38
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-recommended=3.6.0
  - r-rpart=4.1_15
  - r-spatial=7.3_11
  - r-survival=2.44_1.1
  - r-glmnet=2.0_16
  - r-xgboost=0.90.0.2
  - r::r-stringi=1.4.3
  - r::r-stringr=1.4.0
  - r-tidyverse=1.3.0
  - r-Rcpp=1.0.3
  - r-bayesplot=1.7.1
  - r-lme4=1.1_21
  - r-loo=2.1.0
  - r-Matrix=1.2_17
  - r-nlme=3.1_139
  - r-rstan=2.19.2
  - r-rstantools=2.0.0
  - r-shinystan=2.5.0
  - r-survival=2.44_1.1
  - r-rstanarm=2.19.2
  - readline=7.0
  - setuptools=41.6.0
  - sqlite=3.30.1
  - tk=8.6.8
  - tktable=2.10
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7